import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.181.2/build/three.module.js";
import { OrbitControls } from "https://cdn.jsdelivr.net/npm/three@0.181.2/examples/jsm/controls/OrbitControls.js";

const $=id=>document.getElementById(id), KEY="worldchef3d-save-v5";
const RECIPES={
 burger:{name:"Hamburguesa Clásica",icon:"🍔",station:"grill",time:7,base:45,xp:12,req:{bread:1,meat:1,cheese:1,lettuce:1,tomato:1}},
 fries:{name:"Papas Fritas",icon:"🍟",station:"fryer",time:5,base:28,xp:8,req:{potato:2}},
 pizza:{name:"Pizza Pepperoni",icon:"🍕",station:"oven",time:11,base:85,xp:20,req:{dough:1,cheese:2,pepperoni:1,tomato:1}},
 sushi:{name:"Sushi Deluxe",icon:"🍣",station:"prep",time:14,base:130,xp:28,req:{rice:2,fish:1,seaweed:1}},
 steak:{name:"Steak Premium",icon:"🥩",station:"grill",time:12,base:150,xp:30,req:{meat:2}}, soda:{name:"Soda",icon:"🥤",station:"drinks",time:2,base:18,xp:4,req:{syrup:1}}
};
const STATIONS=[["grill","🔥","Parrilla",1,350],["fryer","🍟","Freidora",2,600],["oven","🍕","Horno",3,1000],["prep","🔪","Preparación",5,1800],["drinks","🥤","Bebidas",2,750],["fridge","🧊","Nevera",1,900],["dish","🧼","Lavaplatos",2,1100]];
const INITIAL_INV={bread:20,meat:20,cheese:20,lettuce:20,tomato:20,potato:30,dough:10,pepperoni:10,rice:20,fish:10,seaweed:10,syrup:20};
function fresh(){return{level:1,xp:0,xpGoal:100,cash:500,gems:10,reputation:100,totalOrders:0,restaurantLevel:1,recipeLevels:{burger:1},stations:{grill:1},inv:{...INITIAL_INV},orders:[],prepared:[],selectedOrder:null,activeContract:null,marketing:0,completedContracts:0}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||"null"),d=fresh();if(!x)return d;Object.assign(d,x,{recipeLevels:{...d.recipeLevels,...(x.recipeLevels||{})},stations:{...d.stations,...(x.stations||{})},inv:{...d.inv,...(x.inv||{})}});d.orders=Array.isArray(x.orders)?x.orders:[];d.prepared=Array.isArray(x.prepared)?x.prepared:[];return d}catch{return fresh()}}
let S=load(), cooking=false;
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9eb7c4);scene.fog=new THREE.Fog(0x9eb7c4,13,30);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,100);camera.position.set(8,8,10);
const renderer=new THREE.WebGLRenderer({canvas:$("game"),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;
const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.minDistance=8;controls.maxDistance=16;controls.minPolarAngle=.7;controls.maxPolarAngle=1.25;controls.target.set(0,1,0);
scene.add(new THREE.HemisphereLight(0xffffff,0x405060,2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(4,10,5);sun.castShadow=true;scene.add(sun);
function box(w,h,d,c,x,y,z){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:c,roughness:.75}));o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;scene.add(o);return o}
function cyl(r,h,c,x,y,z){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,20),new THREE.MeshStandardMaterial({color:c,roughness:.7}));o.position.set(x,y,z);o.castShadow=true;scene.add(o);return o}
box(14,.25,12,0x3b424b,0,-.15,0);box(14,4,.25,0x22272f,0,2,-5.8);box(.25,4,12,0x252a32,-7,2,0);box(.25,4,12,0x252a32,7,2,0);
box(5,.25,2.2,0x8b6b45,-3,1.6,-1.6);box(2.8,.25,2.2,0x8b6b45,3,1.6,-1.6);
for(let i=0;i<4;i++){let x=-5+i*3.3;box(2.7,1,1,0x15181d,x,.5,-4.3);cyl(.27,.35,0x5c626a,x-.65,1.18,-4.3);cyl(.27,.35,0x5c626a,x+.65,1.18,-4.3)}
for(let k=0;k<3;k++){let x=-4+k*4;box(.7,.9,.7,0x9b673e,x,.45,3);cyl(.65,.12,0x6d4c35,x,.95,2.7)}
function stationLevel(k){return S.stations[k]||0} function unlocked(id){return stationLevel(RECIPES[id].station)>0}
function recipeValue(id){const r=RECIPES[id],lv=S.recipeLevels[id]||1;return Math.round(r.base*(1+(lv-1)*.2))}
function ok(id){return Object.entries(RECIPES[id].req).every(([k,v])=>(S.inv[k]||0)>=v)}
function consume(id){Object.entries(RECIPES[id].req).forEach(([k,v])=>S.inv[k]-=v)}
function addOrder(){const pool=Object.keys(RECIPES).filter(unlocked),id=pool[Math.floor(Math.random()*pool.length)]||"burger",vip=Math.random()<.07,r=RECIPES[id],t=(vip?48:58)+Math.random()*12;S.orders.push({id:crypto.randomUUID(),recipe:id,vip,time:t,left:t,reward:Math.round(recipeValue(id)*(vip?2:1))});if(!S.selectedOrder)S.selectedOrder=S.orders[0].id;renderOrders()}
function renderOrders(){$("orders").innerHTML=S.orders.map(o=>{const r=RECIPES[o.recipe],p=Math.max(0,o.left/o.time);return '<button class="order '+(o.vip?"vip ":"")+(o.id===S.selectedOrder?"selected":"")+'" data-order="'+o.id+'"><div class="order-head"><span>'+(o.vip?"💎 VIP":"🧑 Cliente")+'</span><span>'+r.icon+" "+r.name+'</span></div><div class="order-items">'+Object.entries(r.req).map(([k,v])=>v+"× "+k).join(" · ")+'</div><div class="timer"><span style="transform:scaleX('+p+')"></span></div><div class="order-reward"><span>'+(o.vip?"2× ":"")+"🪙 $"+o.reward+'</span><span>'+Math.ceil(o.left)+"s</span></div></button>"}).join("");$("orders").querySelectorAll("[data-order]").forEach(b=>b.onclick=()=>{S.selectedOrder=b.dataset.order;renderOrders();update()})}
function toast(t){const e=$("toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1900)}
function update(){const o=S.orders.find(x=>x.id===S.selectedOrder)||S.orders[0],id=o?.recipe||Object.keys(RECIPES).find(unlocked)||"burger",r=RECIPES[id],lv=stationLevel(r.station);$("level").textContent=S.level;$("cash").textContent="$"+S.cash.toLocaleString();$("gems").textContent=S.gems;$("rep").textContent=S.reputation+"%";$("xpBar").style.width=Math.min(100,S.xp/S.xpGoal*100)+"%";$("xpText").textContent=S.xp+" / "+S.xpGoal+" XP";$("stationName").textContent=STATIONS.find(x=>x[0]===r.station)?.[2]||"Parrilla";$("stationInfo").textContent="Nivel "+lv+" · "+r.time+"s";$("cookBtn").innerHTML="COCINAR "+r.icon+" "+r.name.toUpperCase()+" <span>"+r.time+"s</span>";$("ingredients").innerHTML=Object.entries(r.req).map(([k,v])=>'<div class="ingredient">'+k+'<small>'+v+" · "+(S.inv[k]||0)+" disponibles</small></div>").join("");$("restaurantLevel").textContent=S.restaurantLevel;$("preparedCount")&&($("preparedCount").textContent=S.prepared.length);save()}
function gainXP(n){S.xp+=n;while(S.xp>=S.xpGoal){S.xp-=S.xpGoal;S.level++;S.xpGoal=Math.floor(S.xpGoal*1.5);toast("⭐ Nivel "+S.level+" desbloqueado")}checkRestaurant()}
function checkRestaurant(){const target=Math.min(20,1+Math.floor(S.totalOrders/15));if(target>S.restaurantLevel&&S.cash>=target*500&&S.reputation>=80){S.cash-=target*500;S.restaurantLevel=target;toast("🏪 Restaurante nivel "+target+"!")}}
function cook(){if(cooking)return;const o=S.orders.find(x=>x.id===S.selectedOrder)||S.orders[0],id=o?.recipe||"burger",r=RECIPES[id];if(!unlocked(id)){toast("🔒 Estación bloqueada");return}if(!ok(id)){toast("⚠️ Faltan ingredientes para "+r.name);return}consume(id);cooking=true;$("cookBtn").disabled=true;const duration=Math.max(2,r.time-(stationLevel(r.station)-1)*.8),start=performance.now();function tick(now){const left=duration-(now-start)/1000;if(left<=0)return finish(id);$("cookBtn").innerHTML="🔥 COCINANDO "+Math.ceil(left)+"s";requestAnimationFrame(tick)}requestAnimationFrame(tick);update()}
function finish(id){cooking=false;$("cookBtn").disabled=false;S.prepared.push({recipe:id,created:Date.now()});if(S.activeContract)S.activeContract.done=Math.min(S.activeContract.need,S.activeContract.done+1);const o=S.orders.find(x=>x.id===S.selectedOrder)||S.orders[0],r=RECIPES[id];if(o&&o.recipe===id){serve(o)}else toast("🍽️ "+r.name+" preparada. Selecciona el cliente correcto y pulsa SERVIR.");update()}
function serve(o){const r=RECIPES[o.recipe],idx=S.prepared.findIndex(x=>x.recipe===o.recipe);if(idx<0){toast("Falta preparar "+r.name);return}S.prepared.splice(idx,1);S.cash+=o.reward;S.totalOrders++;gainXP(r.xp*(o.vip?2:1));S.orders=S.orders.filter(x=>x.id!==o.id);S.selectedOrder=S.orders[0]?.id||null;toast((o.vip?"💎 VIP satisfecho · ":"")+"Orden servida +$"+o.reward);setTimeout(addOrder,1200);renderOrders();update()}
function serveSelected(){const o=S.orders.find(x=>x.id===S.selectedOrder)||S.orders[0];if(!o)return toast("No hay cliente seleccionado");serve(o)}
function buyIngredient(k){if(S.cash<25)return toast("No tienes suficiente dinero");S.cash-=25;S.inv[k]=(S.inv[k]||0)+10;update();modal("inventory")}
function modal(kind){$("modal").classList.remove("hidden");let html="";
if(kind==="inventory")html="<h2>📦 Inventario</h2><p>Compra lotes de 10.</p><div class='list'>"+Object.entries(S.inv).map(([k,v])=>'<div class="list-row"><div class="main"><b>'+k+'</b><small>'+v+" unidades</small></div><button class='mini-btn green' data-buy='"+k+"'>$25 +10</button></div>").join("")+"</div>";
else if(kind==="upgrades")html="<h2>🔧 Cocina</h2><p>Las estaciones reducen tiempos y desbloquean recetas.</p><div class='list'>"+STATIONS.map(s=>{const[id,ic,n,req,cost]=s,lv=stationLevel(id),price=lv?Math.round(cost*(lv+1)):cost;return '<div class="list-row '+(!lv&&S.level<req?"locked":"")+'"><div class="main"><b>'+ic+" "+n+'</b><small>'+(lv?"Nivel "+lv+" → "+(lv+1):"Desbloqueo nivel "+req)+'</small></div><button class="mini-btn green" data-st="'+id+'" '+(!lv&&S.level<req?"disabled":"")+'>'+price.toLocaleString()+"</button></div>"}).join("")+"</div>";
else if(kind==="recipes")html="<h2>📖 Recetas</h2><div class='list'>"+Object.entries(RECIPES).map(([id,r])=>{const lv=S.recipeLevels[id]||0,locked=!unlocked(id);return '<div class="list-row '+(locked?"locked":"")+'"><div class="main"><b>'+r.icon+" "+r.name+'</b><small>'+(locked?"🔒 Requiere estación "+r.station:"Nivel "+(lv||1)+" · $"+recipeValue(id)+" por orden")+'</small></div><button class="mini-btn '+(!locked?"green":"")+'" data-rec="'+id+'">'+(locked?"🔒":"MEJORAR $"+500*(lv||1))+"</button></div>"}).join("")+"</div>";
else if(kind==="contracts"){const a=S.activeContract;html="<h2>📋 Contratos</h2><p>Produce platos reales dentro del límite de tiempo.</p>"+(a?'<div class="contract active"><b>📦 '+a.name+'</b><small>Progreso '+a.done+"/"+a.need+" · "+Math.ceil(a.left/60)+" min</small><div class='progress'><span style='width:"+(a.done/a.need*100)+"%'></span></div></div>":"<div class='list'>"+[["🎂 Cumpleaños",20,2500,1],["🏢 Corporativo",60,8500,3],["👽 Galáctico",200,35000,8]].map(c=>'<div class="list-row"><div class="main"><b>'+c[0]+'</b><small>'+c[1]+" platos · 10 min · Restaurante "+c[3]+'</small></div><button class="mini-btn green" data-contract="'+c[1]+"|"+c[2]+"|"+c[3]+"|"+c[0]+'">ACEPTAR</button></div>').join("")+"</div>")};
else if(kind==="world")html="<h2>🌎 Mundo</h2><div class='list'>"+[["🇺🇸 Nueva York",1],["🇯🇵 Tokio",11],["🇫🇷 París",21],["🇨🇳 China",31],["🇦🇷 Argentina",41]].map(c=>'<div class="list-row '+(S.level>=c[1]?"":"locked")+'"><div class="main"><b>'+c[0]+'</b><small>'+(S.level>=c[1]?"Disponible":"Nivel "+c[1])+'</small></div><button class="mini-btn">'+(S.level>=c[1]?"ENTRAR":"🔒")+"</button></div>").join("")+"</div>";
else html="<h2>🏪 Restaurante</h2><p>Reputación ⭐ "+S.reputation+"% · Nivel "+S.restaurantLevel+"</p><div class='list'><div class='list-row'><div class='main'><b>Pedidos completados</b><small>"+S.totalOrders+"</small></div></div><div class='list-row'><div class='main'><b>Marketing</b><small>Mejora la llegada de clientes.</small></div><button class='mini-btn green' data-marketing='1'>$500</button></div><div class='list-row'><div class='main'><b>Guardar</b><small>Guardado automático en este dispositivo.</small></div></div><div class='list-row'><div class='main'><b>Reiniciar</b><small>Borra todo el progreso.</small></div><button class='mini-btn' data-reset='1'>RESET</button></div></div>";
$("modalContent").innerHTML=html;
$("modalContent").querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>buyIngredient(b.dataset.buy));
$("modalContent").querySelectorAll("[data-st]").forEach(b=>b.onclick=()=>{const id=b.dataset.st,s=STATIONS.find(x=>x[0]===id),lv=stationLevel(id),price=lv?Math.round(s[4]*(lv+1)):s[4];if(S.cash<price)return toast("Necesitas $"+price);if(!lv&&S.level<s[3])return toast("🔒 Necesitas nivel "+s[3]);S.cash-=price;S.stations[id]=(lv||0)+1;toast("🔧 "+s[2]+" mejorada");update();modal("upgrades")});
$("modalContent").querySelectorAll("[data-rec]").forEach(b=>b.onclick=()=>{const id=b.dataset.rec;if(!unlocked(id))return toast("🔒 Primero desbloquea la estación");const lv=S.recipeLevels[id]||1,cost=500*lv;if(S.cash<cost)return toast("Necesitas $"+cost);S.cash-=cost;S.recipeLevels[id]=lv+1;toast("📖 Receta mejorada");update();modal("recipes")});
$("modalContent").querySelectorAll("[data-contract]").forEach(b=>b.onclick=()=>{if(S.activeContract)return toast("Ya tienes un contrato activo");const[need,reward,req,name]=b.dataset.contract.split("|");if(S.restaurantLevel<+req)return toast("🔒 Restaurante nivel "+req);S.activeContract={name,need:+need,reward:+reward,done:0,left:600};toast("📋 Contrato aceptado");update();modal("contracts")});
$("modalContent").querySelector("[data-marketing]")?.addEventListener("click",()=>{if(S.cash<500)return toast("Necesitas $500");S.cash-=500;S.marketing++;toast("📣 Marketing activo");update();modal("restaurant")});
$("modalContent").querySelector("[data-reset]")?.addEventListener("click",()=>{if(confirm("¿Borrar toda la partida?")){localStorage.removeItem(KEY);location.reload()}});
}
$("closeModal").onclick=()=>$("modal").classList.add("hidden");$("inventoryBtn").onclick=()=>modal("inventory");$("contractsBtn").onclick=()=>modal("contracts");$("upgradesBtn").onclick=()=>modal("upgrades");$("recipesBtn").onclick=()=>modal("recipes");$("worldBtn").onclick=()=>modal("world");$("restaurantBtn").onclick=()=>modal("restaurant");$("cookBtn").onclick=cook;$("serveBtn")?.addEventListener("click",serveSelected);
function contractTick(dt){const a=S.activeContract;if(!a)return;a.left-=dt;if(a.left<=0){if(a.done>=a.need){S.cash+=a.reward;S.completedContracts++;gainXP(Math.round(a.reward/80));toast("🏆 Contrato completado +$"+a.reward)}else{S.reputation=Math.max(0,S.reputation-10);toast("❌ Contrato fallido · reputación -10")}S.activeContract=null}}
function loop(now){if(!loop.last)loop.last=now;const dt=(now-loop.last)/1000;loop.last=now;S.orders.forEach(o=>o.left-=dt);const expired=S.orders.filter(o=>o.left<=0);if(expired.length){S.reputation=Math.max(0,S.reputation-expired.length*3);S.orders=S.orders.filter(o=>o.left>0);if(!S.selectedOrder||!S.orders.some(o=>o.id===S.selectedOrder))S.selectedOrder=S.orders[0]?.id||null;expired.forEach((_,i)=>setTimeout(addOrder,700+i*300));toast("😠 Cliente se fue · reputación -"+expired.length*3)}contractTick(dt);renderOrders();update();renderer.render(scene,camera);requestAnimationFrame(loop)}
addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
if(!S.orders.length){addOrder();setTimeout(addOrder,2500);setTimeout(addOrder,5000)}else{S.selectedOrder=S.orders.some(o=>o.id===S.selectedOrder)?S.selectedOrder:S.orders[0].id;renderOrders()}update();requestAnimationFrame(loop);